server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jobs?useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: pers.wong.jobs.entity

file-config:
  path: /var/wangjianhao/musics
  file-size: 50MB

email-config:
  host: smtp.qq.com
  port: 25
  username: 946669782@qq.com
  password: dsqtvtauczbgbfhj